// Assuming the existing content is included here, but with modifications made accordingly

... previous lines ...
...
67:     <img src="./kapitech-logo-white.png" alt="Kapitech Logo" />
...
130:     <img src="./kapitech-logo-white.png" alt="Kapitech Logo" />
...

... following lines ...